env:
  CUDA_VISIBLE_DEVICES: "1"
  PYTORCH_ALLOC_CONF: expandable_segments:True

script: scripts/pld/train_residual_sac_online.py

args:
  env-id: OpenSafeDoor-v2
  obs-mode: rgb
  reward-mode: sparse
  base-policy: remote_openpi
  server: ws://127.0.0.1:8000
  offline-h5-dir: dataset/Pi0_rollout_OpenSafeDoor-v2
  output-dir: outputs/pld/OpenSafeDoor-v2_rolloutdata_visual
  total-env-steps: 250000
  init-critic-checkpoint: outputs/pld/rollout_pretrain_visual/calql_critic.pt
  batch-size: 256
  wandb-enabled: true
  wandb-project: maniskill-pld
  wandb-name: opensafedoor_online_from_calql_visual
  warmup-buffer-path: outputs/pld_warmup_buffer/warmup_buffer_visual_128.npz
  action-scale: 0.1
  otf-backup-actions: 1
  otf-rollout-actions: 1
  use-visual-rl: true
  rl-image-size: 128
  device: cuda:0
  env-device: cuda:0
  checkpoint-name: residual_sac.pt
